### ISSUE TITLE
Please add a reload command

### ISSUE THREAD

**Issue by maizenalegal** [Wiicart/Strings#1]
A reload command would be a pretty useful addition to the plugin.

**Comment by Wiicart** [comment]
I'll look into adding one with the next update.

**Comment by Wiicart** [comment]
I've looked at this, and there will be a reload command for next update, though it might not work for everything.  The way this plugin was written makes it difficult to fully reload everything without major changes, so this is all I can offer.  If you want to fully reload the plugin, I'd suggest installing a plugin like plugman.

**Comment by Wiicart** [comment]
closing
