### ISSUE TITLE
Color perms

### ISSUE THREAD

**Issue by levitskyyy** [Wiicart/Strings#13]
What rights does a player need to have to use this command?

`/chatcolor`

![image](https://github.com/user-attachments/assets/7fa173c3-d9d8-434d-acb9-4f4fc043b7d9)
![image](https://github.com/user-attachments/assets/22e6f32a-ad58-44ba-9a73-25ad4e1044e5)

**Comment by Wiicart** [comment]
`strings.chat.chatcolor`
