### ISSUE TITLE
Mention system

### ISSUE THREAD

**Issue by levitskyyy** [Wiicart/Strings#2]
Please add a mention system! 🥺🙏

This is the only reason why this plugin is not yet installed on my server

### Example
_[ADMIN] levitsky >> hi @player_username!_

**Comment by Wiicart** [comment]
This sounds like a great feature to add.  I'll look into this.

**Comment by levitskyyy** [comment]
> This sounds like a great feature to add. I'll look into this.

I think it's worth adding notification sounds, (music note) when you're mentioned in the chat.

**Comment by Wiicart** [comment]
Alright, I've got a system working.  Won't publish it till this Saturday bc I have things to polish, but I'll attach a jar here if you want it.  You just @ the player then an action bar message will pop up and a sound will play to the pinged player.  Pretty much everything is customizable, and the mention sound can be any sound in the game.  Theres also /mention <on|off> to toggle receiving them.  Perms are strings.mention, strings.mention.all, strings.mention.toggle.  All config options are in the bottom of the config file.  I'll leave this issue open for a bit if you have any other suggestions or find any issues.

https://drive.google.com/file/d/1KdERlPiW__lamaikcYRgtdEhvfMsCqcU/view?usp=sharing
