### ISSUE TITLE
Channels tweks

### ISSUE THREAD

**Issue by AZsSPC** [Wiicart/Strings#4]
What about adding system of channel textings like in `Chatty`?

I'm talking about ability to config own channel prefixes, like `!` for global, `??` for helpop, and any prefered prefix for custom channels

Hope you'll get this idea

**Comment by Wiicart** [comment]
As in if you type ! before your message the message will be sent to global, or if you type ?? it's sent to helpop?

**Comment by AZsSPC** [comment]
Yep, also there way to add unused (comented) channels in config for `nearby` by prefix `.` (in VERY short distance), `anounce` by `$$` - like short version for `/broadcast` with stiled template or something. There a lot ways for use

**Comment by Wiicart** [comment]
I like that idea.  As for the second part, I don’t really understand what you mean about commented channels.  Can you elaborate?

**Comment by AZsSPC** [comment]
i mean write templates in config but not make them active

**Comment by Wiicart** [comment]
Well I was thinking that I'd put the prefixes in the [channels.yml](https://github.com/Wiicart/Strings/blob/main/strings-bukkit/src/main/resources/channels.yml) file.  Where of course, commented out channels would not be affected.

**Comment by AZsSPC** [comment]
maybe we did not understand each other correctly;

prefixes what i'm talking about used like this: 
if player text `??help me` it will send message `help me` to helpop chat, same for another

hope you'll get it

**Comment by Wiicart** [comment]
Yeah, that’s what I thought you meant.  I was thinking the prefixes for each channel could be stored under each channels configuration in the channels.yml file.  I guess alternatively there could be a dedicated file for prefixes.

**Comment by AZsSPC** [comment]
"prefixes for each channel could be stored under each channels configuration" - but i didn't see those?? can you show the lines where thy placed? or you did not make this yet?

**Comment by Wiicart** [comment]
No, I haven’t written anything yet, I’m just talking about the implementation.  I’ve got some things to do tonight so I’ll probably work on this tomorrow.

**Comment by AZsSPC** [comment]
phew, now i understand you, sorry for lot of text for no reason)

**Comment by Wiicart** [comment]
Oh, no problem, thanks for suggesting this.

**Comment by Wiicart** [comment]
Just updating you, I’ve started work on this, but waiting to finish it before committing.  My goal is to release this feature with a new update next weekend.

**Comment by Wiicart** [comment]
https://github.com/Wiicart/Strings/commit/22259793eeb509dc85135a0e6dc480ea7b705bc2


I'm going to use the term "symbol" instead of "prefix".
I've still got to polish some stuff, like removing the symbol at the start of the message but the general idea has been implemented. 

Each channel can have its symbol set in the [channels.yml](https://github.com/Wiicart/Strings/blob/main/strings-bukkit/src/main/resources/channels.yml) file but don't necessarily need to define one.

**Comment by AZsSPC** [comment]
why only one character? is it a kind of optimization or something?

**Comment by Wiicart** [comment]
It’s not.  They’re stored as strings, so practically there’s no limit on length.

**Comment by Wiicart** [comment]
I guess symbol kind of suggests one character, but I feel like “prefix” could cause confusion with other aspects of the channel while “symbol” doesn’t really have that issue

**Comment by AZsSPC** [comment]
oh, okay! I saw that strings are used, but I doubted it a little when reading the config, where it was said that only one character should be used

**Comment by Wiicart** [comment]
Oh, my bad.  I shouldn’t have it like that in the config.  I’ll change it soon.

**Comment by Wiicart** [comment]
https://github.com/Wiicart/Strings/commit/a5e35039ebf57c25cf0ac59163160166b666e90c
Finished up the work, posting the update shortly.
