### ISSUE TITLE
Layout translater

### ISSUE THREAD

**Issue by AZsSPC** [Wiicart/Strings#5]
can be helpful for servers with multinational players:
in several slavic languages used cyrillic alphabet, and while chatting they can write in wrong layout, like this `ghbdtn` - is the `привет` which means `hello`

so, what about add feature by typing `/command` before `ghbdtn` server will send message from player with corrected text? 
there is demo https://azsspc.github.io/projects/layout_translator/

**Comment by Wiicart** [comment]
Sure, however, I have basically no knowledge of Cyrillic.  I can learn about it online but if you're willing to help me work out how to implement this that would probably speed up the process.

**Comment by AZsSPC** [comment]
I'm honored to leave my mark on your project

**Comment by Wiicart** [comment]
You could fork this, just write a class that has a method that takes in a string and returns the translated string then make a PR with that.

**Comment by AZsSPC** [comment]
what is PR?

**Comment by Wiicart** [comment]
Pull request

**Comment by AZsSPC** [comment]
okay then!

**Comment by Wiicart** [comment]
I've been working on a new plugin that has unicode Fonts, and I think it might offer what you're looking for:
![cyrillic](https://github.com/user-attachments/assets/898c2e0c-f206-45c5-86c1-e8fdf507e874)
I plan to release the plugin on Saturday probably

**Comment by levitskyyy** [comment]
> I plan to release the plugin on Saturday probably

Oh nice!

**Comment by Wiicart** [comment]
If interested: 
https://modrinth.com/plugin/fonts
