### ISSUE TITLE
Mentions tab support

### ISSUE THREAD

**Issue by levitskyyy** [Wiicart/Strings#7]
![image](https://github.com/user-attachments/assets/4752da37-4435-490e-b61e-d053efa113db)

Maybe add TAB button support for mentions?

**Comment by AZsSPC** [comment]
ooo, thats a one-line solution, just take players nicknames and use `.map()`  function to concat it with `"@"`, sipliest function

**Comment by Wiicart** [comment]
While I like this idea, from what I can tell, it’s impossible to tab complete chat if it’s not a command. https://www.spigotmc.org/threads/use-tabcomplete-in-the-chat-not-a-command.512627/

**Comment by levitskyyy** [comment]
> While I like this idea, from what I can tell, it’s impossible to tab complete chat if it’s not a command. https://www.spigotmc.org/threads/use-tabcomplete-in-the-chat-not-a-command.512627/

I saw this feature once in another plugin

**Comment by Wiicart** [comment]
If you can find it and send it to me I'd be glad to take a look at it.

**Comment by Wiicart** [comment]
Up until 1.13 this [Event](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerChatTabCompleteEvent.html) worked, but it's now deprecated and there's no replacement.

**Comment by Wiicart** [comment]
Does not appear possible
