### ISSUE TITLE
Setting world specific chats?

### ISSUE THREAD

**Issue by BlueNightFury46** [Wiicart/Strings#9]
Is there a way to specify a world beneath a channel, or do I just add `type: 'world'` to a parent channel within channels.yml? Does the `type: 'world'` tag work without specifiying a world?

Thanks

**Comment by Wiicart** [comment]
This is the example from the channels.yml: 

`  
world2:
    format: "{prefix}{displayname}{suffix} &7» {message}"
    default-color: "&f"
    call-event: true
    filter-profanity: false
    block-urls: false
    cooldown: false
    type: world
    world: "world2"
    membership: default
    priority: 10
    symbol: "^"
  `
  For a world to be a worldchannel, all you need is to set the `type` to `world` and the `world` to the name of the world.
